apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dodo-payments-ingress
  namespace: default
  annotations:
    # Use the AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # SSL/HTTPS Configuration
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:374364498316:certificate/603e4b59-fe7e-4225-8403-747b31e0702e
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: app.urtechmitra.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: api.urtechmitra.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
    - host: grafana.urtechmitra.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-grafana # Ensure this matches your monitoring namespace service
                port:
                  number: 80